#!/bin/bash

sudo pip3 install spotipy

git clone https://github.com/hzeller/rpi-rgb-led-matrix.git

cd ./rpi-rgb-led-matrix 

sudo make

cd ./bindings/python

sudo apt-get update && sudo apt-get install python3-dev python3-pillow -y
sudo make build-python PYTHON=$(command -v python3)
sudo make install-python PYTHON=$(command -v python3)

cd ../../../

sudo rm -r ./rpi-rgb-led-matrix

make

chmod 777 ./patterns ./.text ./.play_flag.txt ./.album_art.jpg
chmod +x ./album_prod.py
