#!/bin/bash

apt-get install pip3 
apt-get install git  
pip3 install spotipy

git clone https://github.com/hzeller/rpi-rgb-led-matrix.git

cd ./rpi-rgb-led-matrix 

make

cd ./bindings/python

apt-get update && sudo apt-get install python3-dev python3-pillow -y
make build-python PYTHON=$(command -v python3)
make install-python PYTHON=$(command -v python3)

cd ../../../

rm -r ./rpi-rgb-led-matrix

make

chmod 777 ./patterns ./.text ./.play_flag.txt ./.album_art.jpg
chmod +x ./album_prod.py
