#!/bin/bash

apt-get install python3-pip -y 
apt-get install git -y  
pip3 install spotipy

git clone https://github.com/hzeller/rpi-rgb-led-matrix.git

cd ./rpi-rgb-led-matrix 

make

cd ./bindings/python

apt-get update && sudo apt-get install python3-dev python3-pillow -y
make build-python PYTHON=$(command -v python3)
make install-python PYTHON=$(command -v python3)

cd ../../../

rm -r ./rpi-rgb-led-matrix

make
